(setq byte-compile-warnings '(not obsolete))
(setq warning-suppress-log-types '((comp) (bytecomp)))
(setq native-comp-async-report-warnings-errors 'silent)
(setq inhibit-startup-echo-area-message (user-login-name))
;(setq frame-resize-pixelwise t)
(setq default-frame-alist '((fullscreen . maximized)
			    (ns-appearance . dark)
			    (ns-trasparent-titlebar . t)))
